# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_file'),
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='beginDate',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='id',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='name',
        ),
        migrations.AddField(
            model_name='exam',
            name='activity_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.Activity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='begin_date',
            field=models.DateField(default=None, verbose_name='Begin of Course Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=300, verbose_name='Answer'),
        ),
    ]
