# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 04:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20161115_1936'),
        ('exam', '0002_auto_20161117_0009'),
    ]

    operations = [
    ]
