# Generated by Django 2.2 on 2019-06-21 15:19

from django.db import migrations, models
import django.db.models.deletion
import file_link.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileLink',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='topics.Resource')),
                ('file_content', models.FileField(blank=True, upload_to='files/', validators=[file_link.models.validate_file_extension], verbose_name='File')),
            ],
            options={
                'verbose_name': 'File Link',
                'verbose_name_plural': 'File Links',
            },
            bases=('topics.resource',),
        ),
    ]
