# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-24 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import file_link.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0007_auto_20170123_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileLink',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='topics.Resource')),
                ('file_content', models.FileField(upload_to='files/', validators=[file_link.models.validate_file_extension], verbose_name='File')),
            ],
            options={
                'verbose_name': 'File Link',
                'verbose_name_plural': 'File Links',
            },
            bases=('topics.resource',),
        ),
    ]
