# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import file_link.models


class Migration(migrations.Migration):

    dependencies = [
        ('file_link', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filelink',
            name='file_content',
            field=models.FileField(blank=True, upload_to='files/', validators=[file_link.models.validate_file_extension], verbose_name='File'),
        ),
    ]
