# Generated by Django 2.2 on 2019-06-21 15:19

from django.db import migrations, models
import django.db.models.deletion
import pdf_file.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='topics.Resource')),
                ('file', models.FileField(upload_to='files/', validators=[pdf_file.models.validate_file_extension], verbose_name='File')),
            ],
            options={
                'verbose_name': 'PDFFile',
                'verbose_name_plural': 'PDFFiles',
            },
            bases=('topics.resource',),
        ),
    ]
