# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pdf_file.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0007_auto_20170123_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='topics.Resource')),
                ('file', models.FileField(upload_to='/files', validators=[pdf_file.models.validate_file_extension], verbose_name='File')),
            ],
            options={
                'verbose_name': 'PDFFile',
                'verbose_name_plural': 'PDFFiles',
            },
            bases=('topics.resource',),
        ),
    ]
