# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-21 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Birth Date'),
            preserve_default=False,
        ),
    ]
