# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-21 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20161021_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='curriculum',
            field=models.FileField(null=True, upload_to='users/curriculum/', verbose_name='Curriculum'),
        ),
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Institution where he had titration'),
        ),
        migrations.AddField(
            model_name='user',
            name='titration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Titration'),
        ),
        migrations.AddField(
            model_name='user',
            name='year_titration',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Year of titration'),
        ),
    ]
