# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-23 05:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20161222_1806'),
        ('users', '0003_auto_20161222_1505'),
    ]

    operations = [
    ]
