# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-21 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20161021_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='curriculum',
            field=models.FileField(blank=True, null=True, upload_to='users/curriculum/', verbose_name='Curriculum'),
        ),
    ]
