# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-03 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20161222_1806'),
        ('users', '0003_auto_20161222_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_support',
            field=models.BooleanField(default=False, verbose_name='Support'),
        ),
    ]
