# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160728_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_profile',
            field=models.IntegerField(blank=True, choices=[(1, 'Professor'), (2, 'Aluno')], null=True, verbose_name='Tipo'),
        ),
    ]
