# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20160908_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/', verbose_name='Image'),
        ),
    ]
