# Generated by Django 5.2.12 on 2026-04-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("hrbac", "0001_initial"),
  ]

  operations = [
    migrations.AddField(
      model_name="role",
      name="is_editable",
      field=models.BooleanField(default=True),
    ),
    migrations.AddField(
      model_name="role",
      name="is_removable",
      field=models.BooleanField(default=True),
    ),
  ]
