# Generated by Django 5.2.12 on 2026-04-05 19:46

from django.db import migrations


def create_default_roles(apps, schema_editor):
  Role = apps.get_model("hrbac", "Role")

  data = [
    {
      "name": "Admin",
      "description": "Administrador do sistema",
      "is_editable": False,
      "is_removable": False,
    },
    {
      "name": "Coordenador",
      "description": "Coordenador de um assunto",
      "is_editable": True,
      "is_removable": False,
    },
    {
      "name": "Professor",
      "description": "Professor de um assunto",
      "is_editable": True,
      "is_removable": False,
    },
    {
      "name": "Aluno",
      "description": "Aluno de um assunto",
      "is_editable": True,
      "is_removable": False,
    },
  ]

  for role_data in data:
    Role.objects.get_or_create(**role_data)


class Migration(migrations.Migration):
  dependencies = [
    ("hrbac", "0002_role_is_editable_role_is_removable"),
  ]

  operations = [
    migrations.RunPython(create_default_roles),
  ]
