# Generated by Django 5.2.12 on 2026-04-18 19:08

from django.db import migrations


class Migration(migrations.Migration):
  dependencies = [
    ("hrbac", "0004_20260405_2038_add_permissions_for_admin"),
  ]

  operations = [
    migrations.AlterModelOptions(
      name="role",
      options={"verbose_name": "Papel", "verbose_name_plural": "Papeis"},
    ),
    migrations.AlterModelOptions(
      name="usermodulerole",
      options={
        "verbose_name": "Papel de usuário",
        "verbose_name_plural": "Papeis de usuário",
      },
    ),
  ]
