# Generated by Django 5.2.12 on 2026-04-25 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("contenttypes", "0002_remove_content_type_name"),
    ("hrbac", "0005_alter_role_options_alter_usermodulerole_options"),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.AddField(
      model_name="usermodulerole",
      name="object_id",
      field=models.PositiveIntegerField(default=0),
      preserve_default=False,
    ),
    migrations.AlterUniqueTogether(
      name="usermodulerole",
      unique_together={("user", "module", "object_id")},
    ),
    migrations.CreateModel(
      name="UserGlobalRole",
      fields=[
        (
          "id",
          models.BigAutoField(
            auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
          ),
        ),
        (
          "role",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE, to="hrbac.role"
          ),
        ),
        (
          "user",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
          ),
        ),
      ],
      options={
        "verbose_name": "Papel global de usuário",
        "verbose_name_plural": "Papeis globais de usuário",
        "unique_together": {("user", "role")},
      },
    ),
  ]
