# Generated by Django 2.2 on 2019-06-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pendencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, choices=[('view', 'Visualize'), ('create', 'Create'), ('answer', 'Answer'), ('access', 'Access'), ('participate', 'Participate'), ('finish', 'Finish'), ('submit', 'Submit'), ('start', 'Start')], max_length=100, verbose_name='Action')),
                ('begin_date', models.DateTimeField(blank=True, null=True, verbose_name='Begin Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('limit_date', models.DateTimeField(blank=True, null=True, verbose_name='Limit Date')),
            ],
        ),
    ]
