# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-19 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0005_resource'),
        ('pendencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendencies',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pendencies_resource', to='topics.Resource', verbose_name='Resource'),
        ),
    ]
