# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-20 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendencies', '0002_pendencies_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendencies',
            name='limit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Limit Date'),
        ),
    ]
