# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-24 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendencies', '0003_pendencies_limit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendencies',
            name='action',
            field=models.CharField(blank=True, choices=[('view', 'Visualize'), ('create', 'Create'), ('answer', 'Answer'), ('access', 'Access')], max_length=100, verbose_name='Action'),
        ),
    ]
