# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendencies', '0004_auto_20170124_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendencies',
            name='action',
            field=models.CharField(blank=True, choices=[('view', 'Visualize'), ('create', 'Create'), ('answer', 'Answer'), ('access', 'Access'), ('finish', 'Finish')], max_length=100, verbose_name='Action'),
        ),
    ]
