# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-10-23 19:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pendencies', '0008_auto_20190928_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendencyDone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done_date', models.DateTimeField(blank=True, null=True, verbose_name='Done Date')),
                ('late', models.BooleanField(default=False, verbose_name='Done late')),
                ('pendency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendencies_done', to='pendencies.Pendencies', verbose_name='Pendency')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendency_user', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
        ),
    ]
