# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-21 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import themes.models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0006_auto_20170610_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='themes',
            name='high_contrats_logo',
            field=models.ImageField(blank=True, null=True, upload_to='themes/', validators=[themes.models.validate_img_extension], verbose_name='High Contrast Logo'),
        ),
    ]
