# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-08-30 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import themes.models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0007_themes_high_contrats_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themes',
            name='high_contrats_logo',
        ),
        migrations.AlterField(
            model_name='themes',
            name='high_contrast_logo',
            field=models.ImageField(blank=True, null=True, upload_to='themes/', validators=[themes.models.validate_img_extension], verbose_name='High Contrast Logo'),
        ),
    ]
