# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-21 00:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0007_themes_high_contrats_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='themes',
            old_name='high_contrats_logo',
            new_name='high_contrast_logo',
        ),
    ]
