# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-03 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0008_auto_20180830_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themes',
            name='css_style',
            field=models.CharField(choices=[('green', 'Green'), ('contrast', 'Contrast'), ('red', 'Red'), ('red_green', 'Red/Green'), ('black', 'Black')], default='green', max_length=50, verbose_name='Css Style'),
        ),
    ]
