# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-06 02:58
from __future__ import unicode_literals

from django.db import migrations

def load_news_from_fixture(apps, schema_editor):
    from django.core.management import call_command
    call_command("loaddata", "news")

def delete_news(apps, schema_editor):
    News = apps.get_model("news", "News")
    News.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170610_1512'),
        ('users', '0006_auto_20201001_2032'),
    ]

    operations = [
        migrations.RunPython(load_news_from_fixture, delete_news),
    ]
