# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 15:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161101_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='context',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, verbose_name='Context'),
        ),
    ]
