# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_resource_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.CharField(default='', max_length=100, verbose_name='URL'),
        ),
    ]
