# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160912_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='link',
        ),
    ]
