# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0007_auto_20170123_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('ref_value', models.IntegerField(verbose_name='Referential Value')),
                ('order', models.PositiveSmallIntegerField(null=True, verbose_name='Order')),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='topics.Resource')),
                ('presentation', models.TextField(blank=True, verbose_name='Presentation')),
                ('limit_submission_date', models.DateTimeField(verbose_name='Submission Limit Date')),
            ],
            options={
                'verbose_name_plural': 'Goals',
                'verbose_name': 'Goal',
            },
            bases=('topics.resource',),
        ),
        migrations.AddField(
            model_name='goalitem',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_goal', to='goals.Goals', verbose_name='Goal'),
        ),
    ]
