# Generated by Django 2.2 on 2019-06-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoalItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('ref_value', models.IntegerField(verbose_name='Referential Value')),
                ('order', models.PositiveSmallIntegerField(null=True, verbose_name='Order')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
