# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='limit_submission_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Submission Limit Date'),
        ),
    ]
