# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_auto_20170224_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalitem',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
    ]
