# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-01 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_auto_20170301_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mygoals',
            old_name='goal',
            new_name='item',
        ),
    ]
