# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-14 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_auto_20170301_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='init_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Init Date'),
        ),
    ]
