# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-20 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h5p', '0002_auto_20210410_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='h5p',
            name='file',
            field=models.FileField(default='', upload_to='h5p_resource/', verbose_name='File'),
            preserve_default=False,
        ),
    ]
