# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-12 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h5p', '0003_h5p_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h5p',
            name='file',
            field=models.FileField(upload_to='h5p_resource/', verbose_name='H5P Package'),
        ),
    ]
