BBBBBBB BBBBBBBBBBB

BBBB BBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXX XXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX
    BBBBB BBBBBBBBBB
    XXX XXXXXXXXXXXXXXXXXXXX gettext(u'New Exam') XXXXX
    BBBBBBBB BBBBBBBBBB
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Exam Name') XXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Exam Name') XX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u"Exam's begin date") XXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Begin Date') XX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u"Exam's end date") XXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'End Date') XX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Allow submissions after deadline?') 
          XXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX

    XXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Question Type') XXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX
          XXXXXXX XXXXXXXX XXXXXXXXX gettext(u'Question Type') XXXXXXXXX
          XXXXXXX XXXXXXXXXX gettext(u'Multiple Choice') XXXXXXXXX
          XXXXXXX XXXXXXXXXX gettext(u'True or False') XXXXXXXXX
          XXXXXXX XXXXXXXXXX gettext(u'Gap Filling') XXXXXXXXX
          XXXXXXX XXXXXXXXXX gettext(u'Discursive Question') XXXXXXXXX
        XXXXXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'add question') XXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX gettext(u'Create') XXXXXXXXX
  XXXXXX
XXXXXX
XXXXXXXX
XXX XX X XX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXXXXXX
    XX XXX XXXXX X XXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XX XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XXXX
    XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX
  XXX
XXX
XXX XXXXXXXXXXXXXXXX X XX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
  XXX XXXXXXX X XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX X
  XXXXXXXXX X
  XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXX XXXXXXXXXXXXXXXXX X XXXX X
  XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX X
  XXXXXXXXXX X
  XXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXX
XXX
XXX XXXXXXXXXXXXXXXXXX X XX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
  XXX XXXXXXX X XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX X
  XXXXXXXXX X
  XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX X
  XXXXXXXXXX X
  XXXXXXXXX X
  XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX X
  XXXXXXXXXX X
  XXXXXXXXX X
  XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
  XXXXXXXXXX X
  XXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXX
XXX
XXXXXXXXXXXX X
  XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
XXX
XXXXXXXXX

BBBBBBBB BBBBBBB
