

BBBB BBBB

XXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXX XXXXXXXX
  X
  XXXXXXXXXXXXXXXXXXXXX X
    XXXXXXX XXXXX
  X
XXXXXXXX
XXXX XXXXXXXX XXXXXXX
  XXXX XXXXXXXXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXXX
      XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Question') XXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Question') XXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXXX
          XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX

  XXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Alternatives: T/F') XXXXXXXX
  XXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'New Alternative') XXXXXXXXX
    XXXXXX
  XXXXXX
XXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX
  XXX
  XXXXXX XXX XXXXXXXXX XXXXXX XXXXXX XX XXXX
  XX XXXXXXXXXXX XXXXXXXXXXXX XX XXXXXXXXX XXXX XXXXX X XXXXXXXXXXXXXX XXX XXXXXXXXX
      XXXXXX XXXX
      XXXXXXXXX XX
      XXXXXXX XXXXXXXXX XXXXXX XX X X
        XXX XXXX X XX
        XXXXXXXXXXXX XXX XXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX
      XX
  XXX
XXXXXXXXX

