BBBBBBB BBBBBBBBBBBBBBBBBB

BBBB BBBB BBBBBB BBBBBBBBBBB

BBBBB BBBBBBBBBB
XXXX XXX XXXX XXXXX XXXXXXX  XXX
XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB BBBBBBBBBB

BBBBB BBBBBBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
  BBBBBBBBBB
  BBB BBB BB BBBB
  XXXX XXXXXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBB XXXXXXXXX BBBBBXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX
        XXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX FFFFFFFFF
        XXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
  BBBBBB
XXXXXXX
BBBBBBBB BBBBBBBBBBBB
BBBBB BBBBBBBBBBB
XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX gettext(u'Answer') XXXXXXXXX
XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXX
  XXX
XXXXXXXXX
BBBBBBBB BBBBBBBBBBB
