
BBBB BBBB

XXXX XXXXXXXXXX XXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXX
    XXXXX
    XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
      XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Answer') XX
      XXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Possible answer for the question') XXXXXXX
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXX
    XXXXX
    XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
XXXXXX
