

BBBB BBBB BBBBBBBBBBBBB BBBBBBBBBBB BBBBBB


  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXX




XXXX XXXXX XXXXXXXXX XX XXXXXX XXX XXXXXXX XXX
XXXX XXXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX

      XXXX XXXXX XXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXXXXX

        BBBBB BBBBBBBBBB
        XXXX XXX XXXX XXXXX XXXXXXX  XXX
        XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Create a Poll') XXXXX
        BBBBBBBB BBBBBBBBBB
      XXXXXX
      XXXX XXXXX XXXX XXX
      XXXX XXXXXXXXXXXXXXXXXXX

          BBBBB BBBBBBBBBBBB
        XXXX XXX XXXX XXXX XXXXXXX XXXXXXX  XXX
          XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXX
                    XXXXX
                    XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                  XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXX
                      XXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX BB BBBBBBBBBBBBBBB BB BBBBXXXXXXXX BBBBB XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Question?') XX
                      XXXXX XXXXXXXXXXXXXXXXXXX gettext(u'A Question to be answered') XXXXXXX
                    XXXXXX
                  XXXXXX
                  BB BBBBBBBBBBBBBBBB
                  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                  XXXXX
                      XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                          XXXXXXXXX
                        XXXX
                          BBB BBBBB BB BBBBBBBBBBBBBBBB
                            XXXXXXXXX
                          BBBBBB
                        XXXXX
                      XXXXXX
                  XXXXXX
                  BBBBB
                XXXXXX
                  XXXXX XXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
                    BBBBBBBBBB
                    BBB BBB BB BBBB
                    XXXX XXXXXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBB XXXXXXXXX BBBBBXX
                      XXXX XXXXXXXXXXXXXXXXX
                        XXXXX
                        XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXX
                      XXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
                          XXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Answer') X XXXXXXXFFFFFFFFFXX
                          XXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Possible answer for the question') XXXXXXX
                        XXXXXX
                      XXXXXX
                      XXXX XXXXXXXXXXXXXXXXX
                        XXXXX
                        XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXX
                    XXXXXX
                    BBBBB
                    XXXX XXXXXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBB XXXXXXXXX BBBBBXX
                      XXXX XXXXXXXXXXXXXXXXX
                        XXXXX
                        XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXX
                      XXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
                          XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Answer') XX
                          XXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Possible answer for the question') XXXXXXX
                        XXXXXX
                      XXXXXX
                      XXXX XXXXXXXXXXXXXXXXX
                        XXXXX
                        XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXX
                    XXXXXX
                    BBBBBB
                  XXXXXXX
                  XXXXX
                XXXXXX
              XXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBB XXXXXXXXX BBBBBXX
          XXXXXX XXXXXXXXXXXXXXX
          
          XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX BB BBBBBBBBBBBBBBBBBBBBB BB BBBBXXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBFFFFFFFFFFFFBBBBBBBBBXBBBBBX
          BB BBBBBBBBBBBBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXX
              XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXX
                XXXX
                  BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBB
                    XXXXXXXXX
                  BBBBBB
                XXXXX
              XXXXXX
          XXXXXX
          BBBBB
        XXXXXX

        XXXX XXXXXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBB XXXXXXXXX BBBBBXX
            XXXXXX XXXXXXXXXXXXXXX
            BBBBBBBBBBBB  BBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBB
        XXXXXX
        XXXX XXXXXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBB XXXXXXXXX BBBBBXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXXXXX
              BBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX 
            XXXXXXXX
          XXXXXX
          BB BBBBBBBBBBBBBBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXX
              XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXX
                XXXX
                  BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBB
                    XXXXXXXXX
                  BBBBBB
                XXXXX
              XXXXXX
          XXXXXX
          BBBBB
        XXXXXX

        BBBBBBBB BBBBBBBBBBBB
      XXXXXX

      XXXX XXXXX XXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXXXXX

        XXXX XXXXX XXXXXX XXXXXXX  XXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Close') XXXXXXXXX
        BBBBB BBBBBBBBBBB
        XXXX XXX XXXXXX XXXXXXX XXXXXXX  XXX
        XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX gettext(u'Create') XXXXXXXXX
        BBBBBBBB BBBBBBBBBBB
      XXXXXX

    XXXXXX
  XXXXXX
XXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXX
XX XXXX XX XXX XXX XXXXX XXXX XX XXX X XXXXXXXX XXX XXX XXXXXXXXX
XXXXXXXXX
BBBBB BBBBBBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
XX XXXX XX XXX XXX XXXXX XXXX XX XXX X XXXXXX XXX XXX XXX XXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBXXX
  XXX

  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXX
  XXX
XXXXXXXXX
BBBBBBBB BBBBBBBBBBB


