BBBBBBB BBBBBBBBBBBBBBBBBB

BBBB BBBB BBBBBB

BBBBB BBBBBBBBBB
XXXX XXX XXXX XXXXX XXXXXXX  XXX
XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Delete Poll') XXXXX
BBBBBBBB BBBBBBBBBB

BBBBB BBBBBBBBBBBB
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXX XXX XXXX XXXX XXXXXXX XXXXXXX  XXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
  BBBBBBBBBB
    XXX gettext(u'Are you sure you want to delete the subject')  XXXXXXX
XXXXXXX
BBBBBBBB BBBBBBBBBBBB
BBBBB BBBBBBBBBBB
XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX gettext(u'Delete') XXXXXXXXX
XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXX
  XXX
XXXXXXXXX
BBBBBBBB BBBBBBBBBBB
