BBBBBBB BBBBBBBBBBBBBBBBBB

BBBB BBBB BBBBBBBBBBB BBBBBB

BBBBB BBBBBBBBBB
XXXX XXX XXXX XXXXX XXXXXXX  XXX
XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Update a Poll') XXXXX
BBBBBBBB BBBBBBBBBB

BBBBB BBBBBBBBBBB
XXXX XXX XXXXXX XXXXXXX XXXXXXX  XXX
XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX gettext(u'Update') XXXXXXXXX
BBBBBBBB BBBBBBBBBBB

BBBBB BBBBBBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
XX XXXX XX XXX XXX XXXXX XXXX XX XXX X XXXXXX XXX XXX XXX XXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBXXX
  XXX

  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXX
  XXX
XXXXXXXXX
BBBBBBBB BBBBBBBBBBB
