BBBBBBB BBBBBBBBBBBBBBBBBB

BBBB BBBB BBBBBBBBBBB BBBBBB

BBBBB BBBBB
BBBBBBBB

BBBBB BBBBBBBBBB
XXXX XXX XXXX XXXXX XXXXXXX  XXX
XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB BBBBBBBBBB

BBBBB BBBBBBBBBBBB
XXXX XXX XXXX XXXX XXXXXXX XXXXXXX  XXX
XXXX XXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXX gettext(u'Limit date:')  FFFFFFFFFFFFXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXX gettext(u'Status:') 
      BB BBBBBB
       gettext(u'Poll answered') 
      BBBB
       gettext(u"Poll don't yet answered") 
      BBBBB
  XXXXXX
XXXXXX
BBBBBBBB BBBBBBBBBBBB

BBBBB BBBBBBBBBBB
XXXX XXX XXXXXX XXXXXXX XXXXXXX  XXX
BB BBB BBBBBB
XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX gettext(u'Answer') XXXXXXXXX
BBBBB
BBBBBBBB BBBBBBBBBBB
