BBBBBBB BBBBBBBBBBB

BBBB BBBBBB BBBB BBBBBBBBBBBBBBB BBBBBBBBB
BBBB BBBBBBBBBBBBB

BBBBB BBBBBBBBBB
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBXXXXXXXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBB

    XXX XXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXBBB BBBBBBBBBBBXX gettext(u'Home') XXXXXXXXX
        XXXXXX XXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXX gettext(u'Forum') XXXXX
        BBBB
            XXX XXXXXXXXXXXXXXXXXXXX
        BBBBB
        
    XXXXX
BBBBBBBB

BBBBB BBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX gettext(u'Menu') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX
                XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBXX gettext(u'Profile') XXXXXXXXX
                XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBXX gettext(u'My Courses') XXXXXXXXX
            XXXXX
        XXXXXX
    XXXXXX
    
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Actions') XXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBXX XXX X gettext(u'Forum edited successfully!') XXXX gettext(u'Edit') XXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBXX XXX X gettext(u'Are you sure you want to delete this forum?') XX XBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXX gettext(u'Delete') XXXXXXXXX
                XXXXX
            XXXXXX
        XXXXXX
    BBBBB
BBBBBBBB

BBBBB BBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                    XXXXXXXXX
                    XXXXXXX gettext(u'Description') XXXXX XXXXX
                    XXXXXXX gettext(u'Opened in') XXXXX XXXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXX XX
                XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBBBBBBB
                    BBB BBBBB BB BBBB
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBB
                            BBBBBBBBBBBB BBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB
                        BBBB
                            XXXX XXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBB XXXXXXXXX BBBBB XXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXX
                                    BBBBBBBBBBBB BBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB B BBBBBBBB
                                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                    BB BBBBBBBBBBBB
                                        XXXX XXXXXXXXXXXX
                                            XXX XX
                                            XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                                                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                                XXXXXXXXX
                                                XXXX
                                                    BBB BBBBB BB BBBBBBBBBBBB
                                                        XXXXXXXXX
                                                    BBBBBB
                                                XXXXX
                                            XXXXXX
                                        XXXXXX
                                    BBBBB
                                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX
                                            XX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'send') XXXX
                                        XXXXXXXXX
                                    XXXXXXX
                                XXXXXX
                            XXXXXX
                        BBBBB
                    BBBBBB
                XXXXXXX
                XXX XX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXX
                BBBBBBBBBB BBBBBBB BBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                XXXXXXXX
                    XXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXX XX XXXX XXXXX XXXX XXXX XXX
    XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Forum') XXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Close') XXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX gettext(u'Update') XXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
BBBBBBBB

