BBBB BBBB BBBBBBBBBBBBBBB BBBBBBBBB
BBBB BBBBBBBBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX
            
            XXXX XXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBB BB BBBBBBBBB
                    BBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX
                        XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Edit') XXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBXX XXX X gettext(u'Are you sure you want to delete this forum?') XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Delete') XXXXXXXXX
                        XXXXX
                    XXXXXX
                BBBBB
            XXXXXX
        XXXXX
        XXXXXXX gettext(u'Description') XXXXX XXXXX
        XXXXXXX gettext(u'Opened in') XXXXX XXXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXX
    BBBBBBBBBB BBBBBBB BBBBB
XXXXXX

XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBBBBBBB
    BBB BBBBB BB BBBB
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBB
            BBBBBBBBBBBB BBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB
        BBBB
            XXXX XXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBB XXXXXXXXX BBBBB XXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    BBBBBBBBBBBB BBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB B BBBBBBBB
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBB
                        XXXX XXXXXXXXXXXX
                            XXX XX
                            XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXX
                                XXXX
                                    BBB BBBBB BB BBBBBBBBBBBB
                                        XXXXXXXXX
                                    BBBBBB
                                XXXXX
                            XXXXXX
                        XXXXXX
                    BBBBB
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXX
                    XXXXXXX
                XXXXXX
            XXXXXX
        BBBBB
    BBBBBB
XXXXXXX