# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 00:01
from __future__ import unicode_literals

from django.db import migrations

from django.contrib.postgres.operations import UnaccentExtension

class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20170116_1841'),
    ]

    operations = [
        UnaccentExtension()
    ]