# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-18 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_auto_20170116_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order'], 'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
    ]
