# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-23 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_resource__my_subclass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['order'], 'verbose_name': 'Resource', 'verbose_name_plural': 'Resources'},
        ),
    ]
