# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-17 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0007_auto_20170123_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='all_students',
            field=models.BooleanField(default=True, verbose_name='All Students'),
        ),
    ]
