BBBB BBBBBB BBBBBBBBBBBBB BBBB

XXXX XXXXX XXXXXX XXXX XXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBXX

XXXX XXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Delete File') XXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXX XXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBBBBBBB
                        BB BBBBBBBB
                            BBB BBBBBBB BB BBBBBBBB
                                XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXXXXX
                                    XXXXXXX
                                XXXXXX
                            BBBBBB
                        BBBBB
                        XXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXX
                                 gettext(u'Are you sure to delete ') XX XXXXXXX XXXXXXXXXXXXXXX X  XXXX XX X
                            XXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXX
                                     XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Close') XXXXXXXXX
                                    XXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX
                            XXXXXX
                        XXXXXXXXXXX
                    XXXXXXX
                XXXX XXXX XXXX XXX
              XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX

BBBBB BBBBBBBBBBB
    
    
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXX XXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX
                XXXX XBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXX
                XXXXXX XXXXXX
                XXXXXXXXXXXX XXXXXX
                XXXXXXXXXXXX XXXXXX
                XXXXXXXX XXXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXX
                XX
                XXXXXX XXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXX
                X
            XXX
            XXXXXXXXXXXXXXXXXXXXXXX
          XXX
  XXXXXXXXX
BBBBBBBB BBBBBBBBBBB
XXXX XXXXXXXX XXX