# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-01 02:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0007_auto_20170123_1911'),
        ('subjects', '0017_auto_20180830_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionary',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='topics.Resource')),
                ('data_ini', models.DateField(verbose_name='Init Date')),
                ('data_end', models.DateField(verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'Questionary',
                'verbose_name_plural': 'Questionaries',
            },
            bases=('topics.resource',),
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_questions', models.PositiveSmallIntegerField(null=True, verbose_name='Number of Questions')),
                ('categories', models.ManyToManyField(related_name='questionary_categories', to='subjects.Tag', verbose_name='categories')),
                ('questionary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spec_questionary', to='questionary.Questionary', verbose_name='Questionary')),
            ],
        ),
    ]
