# Generated by Django 2.2 on 2019-06-21 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionary',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='topics.Resource')),
                ('presentation', models.TextField(blank=True, verbose_name='Presentation')),
                ('data_ini', models.DateTimeField(verbose_name='Init Date')),
                ('data_end', models.DateTimeField(verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'Questionary',
                'verbose_name_plural': 'Questionaries',
            },
            bases=('topics.resource',),
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_questions', models.PositiveSmallIntegerField(null=True, verbose_name='Number of Questions')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Is correct?')),
                ('order', models.PositiveSmallIntegerField(null=True, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ini', models.DateTimeField(auto_now_add=True, verbose_name='Init Date')),
                ('last_update', models.DateTimeField(auto_now_add=True, verbose_name='Last update')),
                ('questionary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userquest_questionary', to='questionary.Questionary', verbose_name='Questionary')),
            ],
        ),
    ]
