# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-01 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionary',
            name='presentation',
            field=models.TextField(default='', verbose_name='Presentation'),
            preserve_default=False,
        ),
    ]
