# Generated by Django 2.2 on 2019-06-21 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banco_questoes', '0003_auto_20190621_1219'),
        ('questionary', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquest',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userquest_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='useranswer_alternative', to='banco_questoes.Alternative', verbose_name='Answer'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='useranswer_question', to='banco_questoes.Question', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user_quest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='useranswer_userquest', to='questionary.UserQuest', verbose_name='User Questionary'),
        ),
        migrations.AddField(
            model_name='specification',
            name='categories',
            field=models.ManyToManyField(related_name='questionary_categories', to='subjects.Tag', verbose_name='categories'),
        ),
        migrations.AddField(
            model_name='specification',
            name='questionary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spec_questionary', to='questionary.Questionary', verbose_name='Questionary'),
        ),
    ]
