# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-14 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0002_questionary_presentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionary',
            name='data_end',
            field=models.DateTimeField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='questionary',
            name='data_ini',
            field=models.DateTimeField(verbose_name='Init Date'),
        ),
    ]
