# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-25 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0004_auto_20181014_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquest',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Last update'),
        ),
    ]
