# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_forum_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create Date'),
            preserve_default=False,
        ),
    ]
