# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_forum_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modification Date'),
        ),
        migrations.AddField(
            model_name='post',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modification Date'),
        ),
        migrations.AddField(
            model_name='postanswer',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modification Date'),
        ),
    ]
