# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-04 21:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.TextField(verbose_name='Component (Module / App)')),
                ('context', django.contrib.postgres.fields.jsonb.JSONField(blank=True, verbose_name='Context')),
                ('action', models.TextField(verbose_name='Action')),
                ('resource', models.TextField(verbose_name='Resource')),
                ('user', models.CharField(max_length=100, verbose_name='Actor')),
                ('user_id', models.IntegerField(verbose_name='Actor id')),
                ('user_email', models.EmailField(max_length=254, verbose_name='Actor Mail')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time of action')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
    ]
