# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-06 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['component', 'action', 'resource', 'user_id'], name='log_log_compone_99f5ac_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['user_id', 'datetime'], name='log_log_user_id_fc112f_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['user_id'], name='log_log_user_id_6663ba_idx'),
        ),
    ]
