BBBB BBBBBBBBBBBBB BBBB BBBBBB
XXXXXXXXX XXXXXX XXXXXXXXXXX
XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Create a New Exercise') XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXX XXX
        XXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          BBBBBBBBBB
          BB BBBBBBBB
            BBB BBBBBBB BB BBBBBBBB
                XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX
                    XXXXXXX
                XXXXXX
            BBBBBB
          BBBBB
          BBB BBBBB BB BBBB
              XXXX XXXXX XXXXXXXXXXXXXX
              BB BBBBBBBBBBBBBBBBBBBB
                XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              BBBBB
              BBBBBBBBBBBB BBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBB
              BB BBBBBBBBBBBB
                  XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXXXX
                      XXXX
                          BBB BBBBB BB BBBBBBBBBBBB
                              XXXXXXXXX
                          BBBBBB
                      XXXXX
                  XXXXXX
              BBBBB
            XXXXXX
          BBBBBB
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX gettext(u'Cancel') XXXXXXXXX
          XXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Submit') XXXXXXXXX
        XXXXXX
        XXXX XXXX XXXX XXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
XXXX XXXXXXXX XXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX
            XXXX XBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXX
            XXXXXX XXXXXX
            XXXXXXXXXXXX XXXXXX
            XXXXXXXXXXXX XXXXXX
            XXXXXXXX XXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX
            XX
            XXXXXX XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX X XXXXX XXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX XX X XXXXXXXXXXXXXXXXXXX XX XXXXXX
            X
        XXX
        XXXXXXXXXXXXXXXXXXXXXXX
      XXX
XXXXXXXXX
