BBBB BBBBBB BBBBBBBBBBBBB BBBB

XXXX XXXXX XXXXXX XXXX XXX
XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBXX

XXXX XXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Delete Exercise') XXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXX XXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBBBBBBB
                        XXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXX
                                 gettext(u'Are you sure to delete the exercise ')  XXXXXXXXXXXXXXXXXXX XXXX XX X
                            XXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXX
                                     XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Close') XXXXXXXXX
                                    XXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Delete') XXXXXXXXX
                                XXXXXX
                            XXXXXX
                        XXXXXXXXXXX
                    XXXXXXX
                XXXX XXXX XXXX XXX
              XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXX XXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX
                XXXX XBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXX
                XXXXXX XXXXXX
                XXXXXXXXXXXX XXXXXX
                XXXXXXXXXXXX XXXXXX
                XXXXXXXX XXXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX
                XX
                XXXXXX XXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXX XX XXXXXXXXXX
                X
            XXX
            XXXXXXXXXXXXXXXXXXXXXXX
          XXX
  XXXXXXXXX
XXXX XXXXXXXX XXX
