# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20170402_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkmessages',
            name='text',
            field=models.TextField(blank=True, verbose_name='Message'),
        ),
    ]
