# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-13 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20170407_2251'),
        ('chat', '0003_auto_20170407_2154'),
    ]

    operations = [
    ]
