# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-31 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_merge_20170413_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatvisualizations',
            name='date_viewed',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Date/Time Viewed'),
        ),
        migrations.AddIndex(
            model_name='chatvisualizations',
            index=models.Index(fields=['message', 'user'], name='chat_chatvi_message_4e279b_idx'),
        ),
    ]
