# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailbackend',
            name='default_from_email',
            field=models.EmailField(max_length=254, verbose_name='Default from email'),
        ),
    ]
