BBBBBBB BBBBBBBBBBB

BBBB BBBBBB BBBB BBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBB
    
    
     gettext(u'Mural: General') 

    BBBBBBBBBB  BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB

BBBBB BBBBBBB
	XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXX gettext(u'General')  XXXXXXXXXXX
            XX XXXXXXXXXXXX gettext(u'Per Category')  XXXXXXXXXXX
            XX XXXXXXXXXXXX gettext(u'Per Subject')  XXXXXXXXXXX
        XXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX
    	XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
    		XXXX XXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXXXXXXX
    			XXXX XXXXXXXXXXXXXXXXXXX
	    			XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXX
	    				XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XX
	    			XXXXXX
	    			XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX
	    				XXXXX
	    					XXXX gettext(u'Wish to make a new post?') XXXXX
	    				XXXXXX
	    			XXXXXX
	    		XXXXXX
    		XXXXXX

    		BB BBBBBBBBBBB B B
    		BBBB
    			XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
	                XX XXXXXXXXX XXXXXXXXXXXXX
	                XXXX gettext(u'There are no posts in this mural yet.') XXXXX
	            XXXXXX
    		BBBBB
    	XXXXXX
    	XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
    	XXXXXX
    XXXXXX
BBBBBBBB