# Generated by Django 5.2.12 on 2026-04-05 19:31

import os

from django.contrib.auth import get_user_model
from django.db import migrations

SUPERUSER_EMAIL = os.environ.get("DEFAULT_ADMIN_EMAIL", "admin@localhost")
SUPERUSER_PASSWORD = os.environ.get("DEFAULT_ADMIN_PASSWORD", "admin123")


def create_default_admin(apps, schema_editor):
  UserModel = get_user_model()

  data = {
    "email": SUPERUSER_EMAIL,
    "firstname": "Admin",
    "lastname": "Superuser",
    "password": SUPERUSER_PASSWORD,
  }

  if not UserModel.objects.filter(email=data["email"]).exists():
    admin = UserModel.objects.create(
      email=data["email"],
      firstname=data["firstname"],
      lastname=data["lastname"],
      is_staff=True,
    )

    admin.set_password(data["password"])
    admin.save()


def remove_default_admin(apps, schema_editor):
  UserModel = get_user_model()
  UserModel.objects.filter(email=SUPERUSER_EMAIL).delete()


class Migration(migrations.Migration):
  dependencies = [
    ("users", "0001_initial"),
  ]

  operations = [
    migrations.RunPython(create_default_admin, reverse_code=remove_default_admin),
  ]
