# Generated by Django 5.2.12 on 2026-04-05 19:53

from django.db import migrations


def add_module_permissions(apps, schema_editor):
  Role = apps.get_model("hrbac", "Role")
  Permission = apps.get_model("auth", "Permission")

  admin_role = Role.objects.filter(slug="admin").first()

  if not admin_role:
    return

  userPermissions = Permission.objects.filter(content_type__app_label="users")

  admin_role.permissions.add(*userPermissions)


class Migration(migrations.Migration):
  dependencies = [
    ("users", "0003_alter_account_managers"),
    ("hrbac", "0003_auto_20260405_1646"),
  ]

  operations = [
    migrations.RunPython(add_module_permissions),
  ]
