# Generated by Django 5.2.12 on 2026-04-18 19:08

from django.db import migrations


class Migration(migrations.Migration):
  dependencies = [
    ("users", "0004_auto_20260405_1653"),
  ]

  operations = [
    migrations.AlterModelOptions(
      name="account",
      options={
        "verbose_name": "Conta do usuário",
        "verbose_name_plural": "Contas dos usuários",
      },
    ),
    migrations.AlterModelOptions(
      name="user",
      options={
        "verbose_name": "Perfil do usuário",
        "verbose_name_plural": "Perfis dos usuários",
      },
    ),
  ]
