BBBB BBBBBB BBBB
BBBB BBBBBBBBBBBBB

XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBB BBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	BBBBBBBBBB
	BBB BBBBB BB BBBB
		BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBB
            BBBBBBBBBBBB BBBBB BBBBBBBBBBBBBBBBBBBB
        BBBB
			XXXX XXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBB XXXXXXXXX BBBBB XXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXX
					XXXXXX XXXXXXXXXXXXXXX
					BBBBBBBBBBBB BBBBB BBBBBBBBBBBBBBBBBBBB
					XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
					BB BBBBBBBBBBBB
						XXXX XXXXXXXXXXXX
							XXX XX
							XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
			  					XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
			  						XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		  						XXXXXXXXX
								XXXX
									BBB BBBBB BB BBBBBBBBBBBB
										XXXXXXXXX
									BBBBBB
								XXXXX
							XXXXXX
						XXXXXX
					BBBBB
					BB BBBBBB
						XXXX XXXXXXXXXXXXXXXXXXX
			                 XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Cancel') XXXXXXXXX
			                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX gettext(u'Save changes') XXXXXXXXX
			            XXXXXX
					BBBB
						XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
					        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX
					            XX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'send') XXXX
					        XXXXXXXXX
					    XXXXXXX
					BBBBB
				XXXXXX
			XXXXXX
		BBBBB
	BBBBBB
XXXXXXX