# Generated by Django 2.2 on 2019-06-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_data', models.TextField()),
            ],
            options={
                'verbose_name': 'ReportCSV',
                'verbose_name_plural': 'ReportCSVs',
            },
        ),
        migrations.CreateModel(
            name='ReportXLS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xls_data', models.FileField(upload_to='files/')),
            ],
            options={
                'verbose_name': 'ReportCSV',
                'verbose_name_plural': 'ReportCSVs',
            },
        ),
    ]
