# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20170323_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportxls',
            name='xls_data',
            field=models.FileField(upload_to='excel/'),
        ),
    ]
