# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-26 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20161223_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_father',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
