# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-02 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20170102_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='visible'),
        ),
    ]
