# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-24 15:17
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_exercise', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('end_date', models.DateField(verbose_name='Delivery Date')),
                ('grade', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, null=True)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d')),
                ('allowed', models.BooleanField(default=False, verbose_name='Allowed delivery after end date?')),
                ('file_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_type', to='core.MimeType', verbose_name='Type file')),
            ],
        ),
    ]
