# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_auto_20161117_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do arquivo'),
        ),
    ]
