# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_auto_20161118_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='init_date',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='end_date',
            field=models.DateField(verbose_name='Delivery Date'),
        ),
    ]
