# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_auto_20161121_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='allowed',
            field=models.BooleanField(default=False, verbose_name='Allowed delivery after end date?'),
        ),
    ]
