# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_auto_20161121_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='file',
            field=models.FileField(upload_to='uploads/%Y/%m/%d'),
        ),
    ]
