# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, verbose_name='Identificador')),
                ('objectivies', models.TextField(blank=True, verbose_name='Objetivos')),
                ('content', models.TextField(blank=True, verbose_name='Conteúdo')),
                ('max_students', models.PositiveIntegerField(blank=True, verbose_name='Máximo de Alunos')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('init_register_date', models.DateField(verbose_name='Data de Cadastro (Início)')),
                ('end_register_date', models.DateField(verbose_name='Data de Cadastro (Final)')),
                ('init_date', models.DateField(verbose_name='Data de Início do Curso')),
                ('end_date', models.DateField(verbose_name='Data de Final do Curso')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Imagem')),
            ],
            options={
                'verbose_name_plural': 'Cursos',
                'verbose_name': 'Curso',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, verbose_name='Identificador')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('visible', models.BooleanField(default=True, verbose_name='Visível')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Curso')),
            ],
            options={
                'verbose_name_plural': 'Módulos',
                'verbose_name': 'Módulo',
            },
        ),
    ]
