# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Public'),
        ),
    ]
