# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 03:26
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('subjects', models.ManyToManyField(to='courses.Subject')),
            ],
            options={
                'verbose_name_plural': 'subject categories',
                'verbose_name': 'subject category',
            },
        ),
        migrations.RemoveField(
            model_name='activity',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='material',
            name='create_date',
        ),
    ]
