# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-30 04:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='student',
        ),
        migrations.RemoveField(
            model_name='material',
            name='student',
        ),
        migrations.AddField(
            model_name='activity',
            name='all_students',
            field=models.BooleanField(default=False, verbose_name='All Students'),
        ),
        migrations.AddField(
            model_name='activity',
            name='students',
            field=models.ManyToManyField(related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Students'),
        ),
        migrations.AddField(
            model_name='material',
            name='all_students',
            field=models.BooleanField(default=False, verbose_name='All Students'),
        ),
        migrations.AddField(
            model_name='material',
            name='students',
            field=models.ManyToManyField(related_name='materials', to=settings.AUTH_USER_MODEL, verbose_name='Students'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='courses.Topic', verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='material',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.Topic', verbose_name='Topic'),
        ),
    ]
