# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 22:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20160926_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200, verbose_name='Answer')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Order')),
            ],
            options={
                'verbose_name_plural': 'Answers',
                'verbose_name': 'Answer',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.Activity')),
                ('question', models.CharField(max_length=300, verbose_name='Question')),
            ],
            options={
                'verbose_name_plural': 'Polls',
                'verbose_name': 'Poll',
            },
            bases=('courses.activity',),
        ),
        migrations.AlterField(
            model_name='course',
            name='professors',
            field=models.ManyToManyField(related_name='courses_professors', to=settings.AUTH_USER_MODEL, verbose_name='Professors'),
        ),
        migrations.AddField(
            model_name='answer',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.Poll', verbose_name='Answers'),
        ),
    ]
