# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20161018_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Public'),
            preserve_default=False,
        ),
    ]
