# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20161001_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', s3direct.fields.S3DirectField()),
                ('name', models.CharField(max_length=100)),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='courses.Activity')),
            ],
            options={
                'verbose_name_plural': 'Activitys Files',
                'verbose_name': 'Activity File',
            },
        ),
    ]
