# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 15:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_remove_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coordenator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_coordenator', to=settings.AUTH_USER_MODEL, verbose_name='Coordenator'),
        ),
    ]
