# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20160722_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='no_image.jpg', upload_to='courses/', verbose_name='Imagem'),
        ),
    ]
