# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mymetype'),
        ('courses', '0004_auto_20161011_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.Material')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('content', models.FileField(upload_to='uploads/courses/subject/topic/%Y/%m/%d/')),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='core.MymeType', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Topic file',
                'verbose_name_plural': 'Topic files',
            },
            bases=('courses.material',),
        ),
    ]
