# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 04:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mymetype'),
        ('courses', '0005_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='material_ptr',
        ),
        migrations.RemoveField(
            model_name='file',
            name='typ',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
