# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 04:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_auto_20160916_0126'),
        ('courses', '0012_course_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Resource')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('limit_date', models.DateTimeField(verbose_name='Deliver Date')),
                ('grade', models.IntegerField(verbose_name='grade')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='student')),
            ],
            bases=('core.resource',),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Resource')),
                ('url_field', models.CharField(max_length=300, verbose_name='url')),
            ],
            bases=('core.resource',),
        ),
        migrations.AddField(
            model_name='topic',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='Visible'),
        ),
        migrations.AddField(
            model_name='activity',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='courses.Topic', verbose_name='Topic'),
        ),
    ]
