# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20160916_0001'),
        ('courses', '0013_auto_20160916_0126'),
    ]

    operations = [
    ]
