# Generated by Django 2.2 on 2019-06-21 15:19

from django.db import migrations, models
import django.db.models.deletion
import mural.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/comments/', validators=[mural.models.validate_img_extension], verbose_name='Image')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('edited', models.BooleanField(default=False, verbose_name='Edited')),
            ],
        ),
        migrations.CreateModel(
            name='Mural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_my_subclass', models.CharField(max_length=200)),
                ('action', models.CharField(choices=[('comment', 'Comment'), ('help', 'Ask for Help')], default='comment', max_length=100, verbose_name='Action')),
                ('post', models.TextField(blank=True, verbose_name='Post')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/', validators=[mural.models.validate_img_extension], verbose_name='Image')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('edited', models.BooleanField(default=False, verbose_name='Edited')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MuralFavorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryPost',
            fields=[
                ('mural_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mural.Mural')),
            ],
            options={
                'abstract': False,
            },
            bases=('mural.mural',),
        ),
        migrations.CreateModel(
            name='GeneralPost',
            fields=[
                ('mural_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mural.Mural')),
                ('space', models.IntegerField(blank=True, default=0, verbose_name='Space')),
            ],
            options={
                'abstract': False,
            },
            bases=('mural.mural',),
        ),
        migrations.CreateModel(
            name='SubjectPost',
            fields=[
                ('mural_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mural.Mural')),
            ],
            options={
                'abstract': False,
            },
            bases=('mural.mural',),
        ),
        migrations.CreateModel(
            name='MuralVisualizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=False, verbose_name='Viewed')),
                ('date_viewed', models.DateTimeField(blank=True, null=True, verbose_name='Date/Time Viewed')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visualization_comment', to='mural.Comment', verbose_name='Comment')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visualization_post', to='mural.Mural', verbose_name='Post')),
            ],
        ),
    ]
