# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-04 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mural', '0002_muralvisualizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mural',
            name='action',
            field=models.CharField(choices=[('comment', 'Comment'), ('help', 'Ask for Help')], max_length=100, verbose_name='Action'),
        ),
    ]
