# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mural', '0006_auto_20170209_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edited',
            field=models.BooleanField(default=False, verbose_name='Edited'),
        ),
    ]
