# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mural', '0007_comment_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypost',
            name='space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_category', to='categories.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='subjectpost',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_resource', to='topics.Resource', verbose_name='Resource'),
        ),
    ]
