# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mural', '0008_auto_20170224_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='muralvisualizations',
            name='date_viewed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date/Time Viewed'),
        ),
    ]
