# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-31 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mural', '0009_muralvisualizations_date_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muralvisualizations',
            name='date_viewed',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Date/Time Viewed'),
        ),
        migrations.AddIndex(
            model_name='muralvisualizations',
            index=models.Index(fields=['user', 'post', 'comment'], name='mural_mural_user_id_b35367_idx'),
        ),
    ]
