# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-31 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mural', '0010_auto_20210731_1451'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='muralvisualizations',
            index=models.Index(fields=['user', 'viewed'], name='mural_mural_user_id_987ae3_idx'),
        ),
    ]
