# Generated by Django 2.2 on 2019-06-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_register', models.BooleanField(default=False, verbose_name="Don't allow users to self-register")),
                ('maintence', models.BooleanField(default=False, verbose_name='Put system in maintenance mode')),
            ],
            options={
                'verbose_name': 'Security configuration',
                'verbose_name_plural': 'Security configurations',
            },
        ),
    ]
