# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_auto_20170110_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='maintence',
            field=models.BooleanField(default=False, verbose_name='Put system in maintenance mode'),
        ),
    ]
