# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-23 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_auto_20170112_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='allow_category_edition',
            field=models.BooleanField(default=True, verbose_name="Don't allow coordinators to edit, remove or replicate categories"),
        ),
        migrations.AddField(
            model_name='security',
            name='allow_email_change',
            field=models.BooleanField(default=True, verbose_name="Don't allow users to edit access email"),
        ),
        migrations.AddField(
            model_name='security',
            name='allow_socialname_change',
            field=models.BooleanField(default=True, verbose_name="Don't allow users to edit social name"),
        ),
        migrations.AddField(
            model_name='security',
            name='allow_subject_edition',
            field=models.BooleanField(default=True, verbose_name="Don't allow professors to edit, remove or replicate subejcts"),
        ),
    ]
