# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-23 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_auto_20200823_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='security',
            old_name='allow_category_edition',
            new_name='deny_category_edition',
        ),
        migrations.RenameField(
            model_name='security',
            old_name='allow_email_change',
            new_name='deny_email_change',
        ),
        migrations.RenameField(
            model_name='security',
            old_name='allow_socialname_change',
            new_name='deny_socialname_change',
        ),
        migrations.RenameField(
            model_name='security',
            old_name='allow_subject_edition',
            new_name='deny_subject_edition',
        ),
    ]
