# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-13 20:29
from __future__ import unicode_literals

from django.db import migrations

def create_security_entry(apps, schema_editor):
    Security = apps.get_model("security", "Security")
    new_entry = Security.objects.create(allow_register = True,
        maintence = False
    )

class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_auto_20200823_1643'),
    ]

    operations = [
        migrations.RunPython(create_security_entry),
    ]
