# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-01 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0007_auto_20170123_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='YTVideo',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='topics.Resource')),
                ('url', models.URLField(max_length=250, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'YTVideo',
                'verbose_name_plural': 'YTVideos',
            },
            bases=('topics.resource',),
        ),
    ]
