# Generated by Django 2.2 on 2019-06-21 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log', '0001_initial'),
        ('topics', '0001_initial'),
        ('subjects', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YTVideo',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='topics.Resource')),
                ('url', models.CharField(max_length=250, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'YTVideo',
                'verbose_name_plural': 'YTVideos',
            },
            bases=('topics.resource',),
        ),
        migrations.CreateModel(
            name='UpdateVideoInfoLog',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='log.Log')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube_video.YTVideo')),
            ],
            bases=('log.log',),
        ),
        migrations.CreateModel(
            name='StartYoutubeVideoLog',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='log.Log')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic')),
                ('youtube_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube_video.YTVideo')),
            ],
            bases=('log.log',),
        ),
        migrations.CreateModel(
            name='CreateVideoLog',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='log.Log')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube_video.YTVideo')),
            ],
            bases=('log.log',),
        ),
    ]
