# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-06 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material_delivery', '0002_auto_20210621_2223'),
        ('material_delivery', '0002_auto_20210731_1451'),
    ]

    operations = [
    ]
