# Generated by Django 5.2.12 on 2026-04-18 19:08

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Criar'), ('update', 'Atualizar'), ('delete', 'Deletar'), ('view', 'Visualizar'), ('login', 'Login'), ('logout', 'Logout'), ('watch', 'Assistir'), ('answer', 'Responder'), ('access', 'Acessar'), ('comment', 'Comentar'), ('send_message', 'Enviar mensagem'), ('send_mail', 'Enviar email')], max_length=100, verbose_name='Ação')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora')),
                ('object_id', models.PositiveIntegerField(null=True, verbose_name='ID do objeto')),
                ('is_resource', models.BooleanField(default=False, verbose_name='É recurso?')),
                ('from_system', models.BooleanField(default=False, verbose_name='Originou do sistema?')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='Contexto')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Módulo')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Registro de ação',
                'verbose_name_plural': 'Registros de ações',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='logger_acti_user_id_0ee148_idx'), models.Index(fields=['module', 'object_id'], name='logger_acti_module__0ee97c_idx'), django.contrib.postgres.indexes.GinIndex(fields=['context'], name='actionlog_context_gin_idx')],
            },
        ),
    ]
