# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-19 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0005_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='topics.Resource')),
                ('content', models.TextField(verbose_name='HTML Page Content')),
            ],
            options={
                'verbose_name': 'WebPage',
                'verbose_name_plural': 'WebPages',
            },
            bases=('topics.resource',),
        ),
    ]
