# Generated by Django 2.2 on 2019-06-21 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='topics.Resource')),
                ('content', models.TextField(blank=True, verbose_name='Webpage Content')),
            ],
            options={
                'verbose_name': 'WebPage',
                'verbose_name_plural': 'WebPages',
            },
            bases=('topics.resource',),
        ),
    ]
