# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-20 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='content',
            field=models.TextField(blank=True, verbose_name='Webpage Content'),
        ),
    ]
