# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [

        ('courses', '0002_subject_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.Activity')),
                ('name_avalicao', models.CharField(max_length=100, verbose_name='Name')),
                ('init_date', models.DateField(verbose_name='Begin of Avaliacao Date')),
                ('end_date', models.DateField(verbose_name='End of Avaliacao Date')),
            ],
            options={
                'verbose_name': 'Avaliacao',
                'verbose_name_plural': 'Avaliacoes',
            },
            bases=('courses.activity',),
        ),
    ]
