# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-10-04 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElasticSearchSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=250, verbose_name='Host Url')),
            ],
            options={
                'verbose_name': 'Elastic Search Settings',
                'verbose_name_plural': 'Elastic Search Settings',
            },
        ),
    ]
