# Generated by Django 2.2 on 2019-06-21 15:19

import bulletin.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='topics.Resource')),
                ('content', models.TextField(blank=True, verbose_name='Bulletin Content')),
                ('file_content', models.FileField(blank=True, upload_to='bulletin/goals', validators=[bulletin.models.validate_file_extension], verbose_name='Goals')),
                ('indicators', models.FileField(blank=True, null=True, upload_to='bulletin/indicators', validators=[bulletin.models.validate_file_extension], verbose_name='Relevant Indicators')),
            ],
            options={
                'verbose_name': 'Bulletin',
                'verbose_name_plural': 'Bulletins',
            },
            bases=('topics.resource',),
        ),
    ]
