# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-19 02:17
from __future__ import unicode_literals

import bulletin.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0007_auto_20170123_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='topics.Resource')),
                ('content', models.TextField(blank=True, verbose_name='Bulletin Content')),
                ('file_content', models.FileField(blank=True, upload_to='files/', validators=[bulletin.models.validate_file_extension], verbose_name='File')),
            ],
            options={
                'verbose_name': 'Bulletin',
                'verbose_name_plural': 'Bulletins',
            },
            bases=('topics.resource',),
        ),
    ]
