# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-20 00:33
from __future__ import unicode_literals

import bulletin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='file_content',
            field=models.FileField(blank=True, upload_to='files/', validators=[bulletin.models.validate_file_extension], verbose_name='Bulletin Data (Goals)'),
        ),
    ]
