# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicFile',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.Material')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file_url', models.FileField(upload_to=files.models.file_path, verbose_name='File')),
                ('file_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_files', to='core.MimeType', verbose_name='Type file')),
            ],
            options={
                'verbose_name_plural': 'Files',
                'verbose_name': 'File',
                'ordering': ('-id',),
            },
            bases=('courses.material',),
        ),
    ]
