# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-06 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailSender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('hostname', models.CharField(max_length=200, verbose_name='Host name')),
                ('port', models.IntegerField(verbose_name='Port Number')),
                ('username', models.CharField(max_length=200, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('crypto', models.IntegerField(choices=[(1, 'No'), (2, 'SSL'), (3, 'TLS'), (4, 'TLS, if possible')], verbose_name='Criptografy')),
            ],
            options={
                'verbose_name': 'Mail sender configuration',
                'verbose_name_plural': 'Mail sender configurations',
            },
        ),
    ]
