# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-26 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='markers',
            field=models.ManyToManyField(to='subjects.Marker', verbose_name='markers'),
        ),
    ]
