# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-02 20:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0005_auto_20170102_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='professor',
        ),
        migrations.AddField(
            model_name='subject',
            name='professor',
            field=models.ManyToManyField(blank=True, related_name='professor', to=settings.AUTH_USER_MODEL),
        ),
    ]
