# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-03 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_auto_20170103_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description_brief',
            field=models.TextField(blank=True, verbose_name='simpler_description'),
        ),
    ]
