# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0008_auto_20170103_2044'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marker',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='markers',
            new_name='tags',
        ),
    ]
