# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_auto_20170105_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subscribe_begin',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Begin Subscribe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='subscribe_end',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='End Subscribe'),
            preserve_default=False,
        ),
    ]
