# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 02:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0010_auto_20170109_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subscribe_begin',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Begin Subscribe'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subscribe_end',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='End Subscribe'),
        ),
    ]
