# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-30 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0013_auto_20170120_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='tags',
            field=models.ManyToManyField(blank=True, to='subjects.Tag', verbose_name='tags'),
        ),
    ]
