# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-15 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0014_auto_20170130_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='Name'),
        ),
    ]
