# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-31 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0015_auto_20170815_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
