# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-03-06 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0017_auto_20180830_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='diaply_avatar',
            field=models.BooleanField(default=False, verbose_name='Display avatar to students?'),
        ),
    ]
