# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-03-06 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0018_subject_diaply_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='diaply_avatar',
            new_name='display_avatar',
        ),
    ]
