# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-25 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0019_auto_20200306_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='external_access',
            field=models.BooleanField(default=False, verbose_name='Make available outside Amadeus?'),
        ),
        migrations.AddField(
            model_name='subject',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Price'),
        ),
    ]
