# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-25 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0020_auto_20220425_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='price',
            field=models.TextField(blank=True, default=0.0, verbose_name='Price'),
        ),
    ]
