# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-30 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0007_auto_20170123_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='topics.Resource')),
                ('description', models.TextField(blank=True, verbose_name='simpler_description')),
                ('link_url', models.URLField(verbose_name='Link_URL')),
                ('initial_view', models.BooleanField(default=False, verbose_name='Initial View')),
                ('initial_view_date', models.DateField(default=django.utils.timezone.now, verbose_name='Initial View Date')),
                ('end_view', models.BooleanField(default=False, verbose_name='Initial View')),
                ('end_view_date', models.DateField(default=django.utils.timezone.now, verbose_name='Initial View Date')),
            ],
            options={
                'verbose_name_plural': 'Links',
                'verbose_name': 'Link',
            },
            bases=('topics.resource',),
        ),
    ]
