# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='end_view_date',
            field=models.DateField(verbose_name='Initial View Date'),
        ),
        migrations.AlterField(
            model_name='link',
            name='initial_view_date',
            field=models.DateField(verbose_name='Initial View Date'),
        ),
    ]
