# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-28 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='image',
            field=models.ImageField(blank=True, upload_to='links/'),
        ),
    ]
