# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-16 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_auto_20161116_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_description',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
    ]
