# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_auto_20170201_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='end_view_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Initial View Date'),
        ),
        migrations.AlterField(
            model_name='link',
            name='initial_view_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Initial View Date'),
        ),
    ]
