# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_auto_20170201_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='end_view',
        ),
        migrations.RemoveField(
            model_name='link',
            name='end_view_date',
        ),
        migrations.RemoveField(
            model_name='link',
            name='initial_view',
        ),
        migrations.RemoveField(
            model_name='link',
            name='initial_view_date',
        ),
    ]
