# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0007_auto_20170201_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='description_brief',
        ),
    ]
