BBBB BBBBBBBBBBBBB BBBB

XXXXXXXXX XXXXXX XXXXXXX
XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Create a New Link') XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXX XXX
        XXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          BBBBBBBBBB
          BB BBBBBBBB
              BBB BBBBBBB BB BBBBBBBB
                  XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXXXX
                      XXXXXXX
                  XXXXXX
              BBBBBB
          BBBBB
        BBB BBBBB BB BBBB
            BB BBBBBBBBBBBBBBBBBBBB
              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BBBB
              XXXXXX XXXXXXXXXXXXXXX
            BBBBB
            BBBBBBBBBBBB BBBBB BBBBBBBBBBBBBBBBBBBB
        BBBBBB
        XXXX XXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Cancel') XXXX
          XXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXX
        XXXXXX
        XXXX XXXX XXXX XXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
XXXX XXXXXXXX XXX


XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXX XXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX
            XXXX XBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXX
            XXXXXX XXXXXX
            XXXXXXXXXXXX XXXXXX
            XXXXXXXXXXXX XXXXXX
            XXXXXXXX XXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX
            XXXXXX XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
        XXX
        XXXXXXXXXXXXXXXXXXXXXXX
      XXX
XXXXXXXXX
