BBBB BBBB BBBBBBBBBBBBBBB BBBBBBBBB
BBBB BBBBBBBBBBBBB

XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBBBBBBB
    BBB BBBBB BB BBBB
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBB
            BBBBBBBBBBBB BBBBB BBBBBBBBBBBBBBBBBBBB
        BBBB
            XXXX XXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBB XXXXXXXXX BBBBB XXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    BBBBBBBBBBBB BBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB B BBBBBBBB
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBB
                        XXXX XXXXXXXXXXXX
                            XXX XX
                            XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXX
                                XXXX
                                    BBB BBBBB BB BBBBBBBBBBBB
                                        XXXXXXXXX
                                    BBBBBB
                                XXXXX
                            XXXXXX
                        XXXXXX
                    BBBBB                    
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                 XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Cancel') XXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX gettext(u'Save changes') XXXXXXXXX
            XXXXXX
        BBBBB
    BBBBBB
XXXXXXX