BBBB BBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB

XXXX XXXXXXXXXX XXXXXXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XBBB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'reply') XXXX
                XXXX
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBB BB BBBBBBBBB
                    BBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX
                        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBXX XXX X gettext(u'Post edited successfully!') XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Edit') XXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Remove') XXXXXXXXX
                        XXXXX
                    XXXXXX
                BBBBB
            XXXXXX
        XXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXXXXXX FFFFFFFFF  gettext(u'ago') 
                    BB BBBBBBBBBBBBBBBB
                        XXXX X  gettext(u'Edited') XXXXX
                    BBBBB
                XXXX
            XXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
            BBBBBBBBBBBBBBBB BBBBBBB BBBB
        XXXXXX
    XXXXXX
XXXXXX