# Generated by Django 2.2 on 2019-06-21 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log', '0001_initial'),
        ('topics', '0001_initial'),
        ('subjects', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, verbose_name='Domain')),
            ],
            options={
                'verbose_name': 'Web Conference Setting',
                'verbose_name_plural': 'Web Conferences Setting',
            },
        ),
        migrations.CreateModel(
            name='Webconference',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='topics.Resource')),
                ('presentation', models.TextField(blank=True, verbose_name='Presentation')),
                ('start', models.DateTimeField(verbose_name='Start date/hour')),
                ('end', models.DateTimeField(verbose_name='End date/hour')),
            ],
            options={
                'verbose_name': 'Web Conference',
                'verbose_name_plural': 'Web Conferences',
            },
            bases=('topics.resource',),
        ),
        migrations.CreateModel(
            name='ViewWebConferenceLog',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='log.Log')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic')),
                ('webconference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webconference.Webconference')),
            ],
            bases=('log.log',),
        ),
        migrations.CreateModel(
            name='ViewStatisticsConferenceLog',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='log.Log')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic')),
                ('webconference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webconference.Webconference')),
            ],
            bases=('log.log',),
        ),
        migrations.CreateModel(
            name='UpdateWebConferenceLog',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='log.Log')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic')),
                ('webconference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webconference.Webconference')),
            ],
            bases=('log.log',),
        ),
        migrations.CreateModel(
            name='SendMessageInWebConferenceLog',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='log.Log')),
                ('message', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic')),
                ('webconference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webconference.Webconference')),
            ],
            bases=('log.log',),
        ),
        migrations.CreateModel(
            name='ParticipatingInWebConferenceLog',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='log.Log')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic')),
                ('webconference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webconference.Webconference')),
            ],
            bases=('log.log',),
        ),
        migrations.CreateModel(
            name='InsideViewWebConferenceLog',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='log.Log')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic')),
                ('webconference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webconference.Webconference')),
            ],
            bases=('log.log',),
        ),
        migrations.CreateModel(
            name='InitWebConferenceLog',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='log.Log')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic')),
                ('webconference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webconference.Webconference')),
            ],
            bases=('log.log',),
        ),
        migrations.CreateModel(
            name='EndParticipationInConferenceLog',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='log.Log')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic')),
                ('webconference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webconference.Webconference')),
            ],
            bases=('log.log',),
        ),
        migrations.CreateModel(
            name='DeleteWebConferenceLog',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='log.Log')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic')),
                ('webconference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webconference.Webconference')),
            ],
            bases=('log.log',),
        ),
        migrations.CreateModel(
            name='CreateWebConferenceLog',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='log.Log')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic')),
                ('webconference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webconference.Webconference')),
            ],
            bases=('log.log',),
        ),
    ]
