# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, verbose_name='Domain')),
            ],
            options={
                'verbose_name': 'Conference Setting',
                'verbose_name_plural': 'Conferences Setting',
            },
        ),
    ]
