# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webconference', '0002_conferencesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conferencesettings',
            options={'verbose_name': 'Web Conference Setting', 'verbose_name_plural': 'Web Conferences Setting'},
        ),
    ]
