# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-16 12:12
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations
import webconference.models


class Migration(migrations.Migration):

    dependencies = [
        ('webconference', '0003_auto_20170323_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='webconference',
            name='jitsi_slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', slugify=webconference.models.slugify_jitsi, unique=True, verbose_name='Jitsi Slug'),
        ),
    ]
