# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-19 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_group', '0002_auto_20170118_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentsgroup',
            options={'ordering': ['name'], 'verbose_name': 'Students Group', 'verbose_name_plural': 'Students Groups'},
        ),
    ]
