# Generated by Django 2.2 on 2019-06-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.DateTimeField(blank=True, null=True, verbose_name='Meta')),
                ('level', models.IntegerField(choices=[(1, 'Type 1-A'), (2, 'Type 1-B'), (3, 'Type 2'), (4, 'Type 3')], verbose_name='Type')),
                ('viewed', models.BooleanField(default=False, verbose_name='Visualized')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation Date')),
            ],
        ),
    ]
