# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 18:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pendencies', '0004_auto_20170124_0128'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.DateField(blank=True, null=True, verbose_name='Meta')),
                ('level', models.IntegerField(choices=[(1, 'Type 1-A'), (2, 'Type 1-B'), (3, 'Type 2'), (4, 'Type 3')], verbose_name='Type')),
                ('viewed', models.BooleanField(default=False, verbose_name='Visualized')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation Date')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_pendencies', to='pendencies.Pendencies', verbose_name='Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
