# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-30 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='meta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Meta'),
        ),
    ]
