# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-13 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20170130_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='aware',
            field=models.BooleanField(default=False, verbose_name='Aware'),
        ),
    ]
