# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-13 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_aware'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='aware',
        ),
    ]
