# Generated by Django 2.2 on 2019-06-24 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_log_user'),
        ('subjects', '0002_auto_20190621_1219'),
        ('notifications', '0003_notification_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronNotification',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='log.Log')),
            ],
            bases=('log.log',),
        ),
        migrations.CreateModel(
            name='ViewSubjectHistoryLog',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='log.Log')),
                ('history_page', models.IntegerField()),
                ('searched_term', models.CharField(max_length=200)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject')),
            ],
            bases=('log.log',),
        ),
        migrations.CreateModel(
            name='ViewPendenciesLog',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='log.Log')),
                ('view_page', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject')),
            ],
            bases=('log.log',),
        ),
    ]
