# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-31 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_remove_notification_aware'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='creation_date',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='Creation Date'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'task', 'creation_date'], name='common_filter_idx'),
        ),
    ]
