# Generated by Django 2.2 on 2019-06-26 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20190621_1219'),
        ('log', '0003_log_user'),
        ('goals', '0003_auto_20190621_1219'),
        ('notifications', '0004_cronnotification_viewpendencieslog_viewsubjecthistorylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetGoalLog',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='log.Log')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.Notification')),
            ],
            bases=('log.log',),
        ),
        migrations.CreateModel(
            name='ViewPendenciesHistoryLog',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='log.Log')),
                ('history_page', models.IntegerField(null=True)),
                ('searched_term', models.CharField(max_length=200, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject')),
            ],
            bases=('log.log',),
        ),
        migrations.AlterField(
            model_name='viewpendencieslog',
            name='view_page',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='ViewSubjectHistoryLog',
        ),
    ]
