# Generated by Django 2.2 on 2019-06-21 15:19

import banco_questoes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
                ('alt_img', models.ImageField(blank=True, null=True, upload_to='questions/alternatives', validators=[banco_questoes.models.validate_img_extension], verbose_name='Image')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Is correct?')),
            ],
            options={
                'verbose_name': 'Alternative',
                'verbose_name_plural': 'Alternatives',
            },
        ),
    ]
