# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-08-30 11:50
from __future__ import unicode_literals

import banco_questoes.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0017_auto_20180830_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
                ('alt_img', models.ImageField(blank=True, null=True, upload_to='questions/alternatives', validators=[banco_questoes.models.validate_img_extension], verbose_name='Image')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Is correct?')),
            ],
            options={
                'verbose_name': 'Alternative',
                'verbose_name_plural': 'Alternatives',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(verbose_name='Statement')),
                ('question_img', models.ImageField(blank=True, null=True, upload_to='questions/', validators=[banco_questoes.models.validate_img_extension], verbose_name='Image')),
                ('categories', models.ManyToManyField(related_name='question_categories', to='subjects.Tag', verbose_name='categories')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_subject', to='subjects.Subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.AddField(
            model_name='alternative',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt_question', to='banco_questoes.Question', verbose_name='Question'),
        ),
    ]
