# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-31 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_questoes', '0002_auto_20181001_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='Created At'),
            preserve_default=False,
        ),
    ]
