# Generated by Django 2.2 on 2019-06-21 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banco_questoes', '0002_createquestionindblog_deletequestionindblog_question_replicatequestionindblog_updatequestionindblog'),
        ('subjects', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatequestionindblog',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='replicatequestionindblog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category'),
        ),
        migrations.AddField(
            model_name='replicatequestionindblog',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco_questoes.Question'),
        ),
        migrations.AddField(
            model_name='replicatequestionindblog',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='question',
            name='categories',
            field=models.ManyToManyField(related_name='question_categories', to='subjects.Tag', verbose_name='categories'),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_subject', to='subjects.Subject', verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='deletequestionindblog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category'),
        ),
        migrations.AddField(
            model_name='deletequestionindblog',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco_questoes.Question'),
        ),
        migrations.AddField(
            model_name='deletequestionindblog',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='createquestionindblog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category'),
        ),
        migrations.AddField(
            model_name='createquestionindblog',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco_questoes.Question'),
        ),
        migrations.AddField(
            model_name='createquestionindblog',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='alternative',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt_question', to='banco_questoes.Question', verbose_name='Question'),
        ),
    ]
