# Generated by Django 2.2 on 2019-04-22 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banco_questoes', '0003_question_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternative',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_question', to='banco_questoes.Question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_subject', to='subjects.Subject', verbose_name='Subject'),
        ),
    ]
