BBBB BBBB

XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX

  XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Question') XXXXXXXX


  XXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX


XXXXXX
XXXX XXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Alternatives') XXXXXXXX
  XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXXXXXX
        XXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXX
    XXXXXX
  XXXXXX
XXXXXX
XXXX XXX XXXXXXXXXXX XXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXX
  XXXXXX
XXXXXX
XXXX XXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
XXXXXX
