BBBB BBBB

XXXX XXXXXXXXXX XXXXXXXXXXX X
  XXXX XXXXXXXXXXXXXXXXX
    XXXXX
    XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Write your alternative') XXXXXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXX
    XXXXX
    XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
XXXXXX
